### ISSUE TITLE
Trivial Element

### ISSUE THREAD

**Issue by NicolasW1** [MichielStock/Kronecker.jl#115]
For some situations I've encountered with an arbitrary number of matrices it is practical to have a trivial element `kronecker(A::AbstractMatrix) = A`. Is there some interest/sense to incorporate this into the library?

**Comment by MichielStock** [comment]
Like in #116? Strictly speaking, the Kronecker product is a binary operator but it seems like a logical extension.

**Comment by NicolasW1** [comment]
Yes, perfect! Thanks for adding it so fast.
