### ISSUE TITLE
Copy of `Kronecker.KroneckerProduct` is a `Matrix`

### ISSUE THREAD

**Issue by nathanaelbosch** [MichielStock/Kronecker.jl#126]
Is this the expected behaviour? My intuitive guess would have been that `copy` essentially does
```julia
copy(A::Kronecker.KroneckerProduct) = kronecker(copy(A.A), copy(A.B))
```
(though note that `deepcopy` is one way to get exactly this behaviour).

EDIT: Add a missing `copy`

**Comment by MichielStock** [comment]
I guess `copy(K::Kronecker.KroneckerProduct) = kronecker(K.A, K.B)` would make the most sense here?

**Comment by nathanaelbosch** [comment]
I think `copy` should actually create a new object and allocate new memory, as this is what `copy(A::Matrix)` seems to do too:
```
julia> A = rand(2,2)
2×2 Matrix{Float64}:
 0.595633  0.803728
 0.619281  0.536836

julia> copy(A) == A
true

julia> copy(A) === A
false
```
whereas your suggestion would return the same object:
```
julia> K = kronecker(rand(1,1), rand(1,1))
1×1 Kronecker.KroneckerProduct{Float64, Matrix{Float64}, Matrix{Float64}}:
 0.4546797107928652

julia> copy(K) == K
true

julia> copy(K) === K
true
```

Therefore my suggestion would be (and I just realized I had a typo in my comment above):
```julia
copy(A::Kronecker.KroneckerProduct) = kronecker(copy(A.A), copy(A.B))
```
And while we're at it, it would also be nice to add
```julia
similar(A::Kronecker.KroneckerProduct) = kronecker(similar(A.A), similar(A.B))
```
