### ISSUE TITLE
Could we get a release with the new `copy` functionality?

### ISSUE THREAD

**Issue by nathanaelbosch** [MichielStock/Kronecker.jl#134]
I'm using Kronecker.jl and I do need `copy`, `copy!` and `deepcopy` - so right now I'm doing a bit of type piracy :pirate_flag: But ideally I would like to get rid of this again. Would it be an option to get a new release of Kronecker.jl soon so that we can use those functions? Is there something holding this back?

**Comment by MichielStock** [comment]
Solved in commit 4518212
