### ISSUE TITLE
Do we really need SquareKroneckerMatrices?

### ISSUE THREAD

**Issue by willtebbutt** [MichielStock/Kronecker.jl#24]
Is an extra type for square kronecker matrices really necessary? Unless there's a strong reason to have it that I'm unaware of (square-ness is quite straightforward to test at runtime), it just seems like an unecessary extra type, that makes `kronecker` type-unstable -- it's output is a function of runtime properties of its inputs.

Having a square type is also something of a digression from what `LinearAlgebra` does, which also checks square-ness dynamically, rather than statically.

**Comment by MichielStock** [comment]
You might be right. Sounded a good idea at the time, because there are many
functions only relevant for some functions, but is is probably better to
just test for those.

Will remove the type and add the tests where required.

**Comment by willtebbutt** [comment]
Resolved by #28
