### ISSUE TITLE
Should dense arrays be made sparse in KroneckerSums?

### ISSUE THREAD

**Issue by elisno** [MichielStock/Kronecker.jl#27]
This is related to #26.

`collect(K::AbstractKroneckerProduct)` calls `kron` 

https://github.com/MichielStock/Kronecker.jl/blob/4897b960e9d5b3c7286b484e50efa5e682dc1fa4/src/base.jl#L167-L170

but `collect(K::AbstractKroneckerSum)` writes to an `Array`.

https://github.com/MichielStock/Kronecker.jl/blob/4897b960e9d5b3c7286b484e50efa5e682dc1fa4/src/kroneckersum.jl#L110-L116

The following snippet compares `collect` for kronecker sums using `⊕` and `kron`.
The sparse `kron` methods are considerably faster at evaluating the sum.
Note that the test in the last line fails.

```julia
using Kronecker, SparseArrays, Test

N = 10
# Similar
A,B,C = (rand(N,N) for _ in 1:3)
IA,IB,IC = oneunit.((A,B,C))
As,Bs,Cs = sparse.((A,B,C))
IAs,IBs,ICs = oneunit.((As,Bs,Cs))

# Compare dense and sparse collections to ⊕
@test collect(As ⊕ Bs ⊕ Cs) == kron(As,IBs,ICs) + kron(IAs,Bs,ICs) + kron(IAs,IBs,Cs)
@test collect(As ⊕ Bs ⊕ Cs) == kron(A,IB,IC) + kron(IA,B,IC) + kron(IA,IB,C)

# Warmup dense collection
collect(A ⊕ B ⊕ C)

# Timing dense and sparse collections with ⊕ and kron
@time collect(A ⊕ B ⊕ C)
@time collect(As ⊕ Bs ⊕ Cs)
@time kron(A,IB,IC) + kron(IA,B,IC) + kron(IA,IB,C)
@time kron(As,IBs,ICs) + kron(IAs,Bs,ICs) + kron(IAs,IBs,Cs)

# Checking collection types for ⊗, ⊕ and kron
@test kron(As,IB) isa SparseMatrixCSC
@test collect(As ⊗ Bs) isa SparseMatrixCSC # true for kronecker()
@test (kron(As,IB,IC) + kron(IA,Bs,IC) + kron(IA,IB,Cs)) isa SparseMatrixCSC
@test collect(As ⊕ Bs) isa SparseMatrixCSC # false for kroneckersum()
```

These are the timings I get (post-warmup):

```julia
  0.036748 seconds (8 allocations: 7.630 MiB)
  0.036204 seconds (8 allocations: 7.630 MiB, 18.14% gc time)
  0.044283 seconds (19 allocations: 30.747 MiB, 50.08% gc time)
  0.000488 seconds (46 allocations: 1.281 MiB)
```

**Comment by elisno** [comment]
For curiosity's sake, I added some more benchmarks for higher and lower orders

<details>
<summary>Click to expand!</summary>

Here I shut down the last test

```julia
using Kronecker, SparseArrays, Test

N = 10
A,B,C,D = (rand(N,N) for _ in 1:4)
IA,IB,IC,ID = oneunit.((A,B,C,D))
As,Bs,Cs,Ds = sparse.((A,B,C,D))
IAs,IBs,ICs,IDs = oneunit.((As,Bs,Cs,Ds))

# Compare dense and sparse collections to ⊕
@test collect(As ⊕ Bs ⊕ Cs ⊕ Ds) == kron(As,IBs,ICs,IDs) + kron(IAs,Bs,ICs,IDs) + kron(IAs,IBs,Cs,IDs) + kron(IAs,IBs,ICs,Ds)
@test collect(As ⊕ Bs ⊕ Cs ⊕ Ds) == kron(A,IB,IC,ID) + kron(IA,B,IC,ID) + kron(IA,IB,C,ID) + kron(IA,IB,IC,D)

# Warmup dense collection
collect(A ⊕ B ⊕ C ⊕ D)

# Timing dense and sparse collections with ⊕ and kron
begin
    println("\norder 2")
    @time collect(A ⊕ B)
    @time collect(As ⊕ Bs)
    @time kron(A,IB) + kron(IA,B)
    @time kron(As,IBs) + kron(IAs,Bs)


    println("\norder 3")
    @time collect(A ⊕ B ⊕ C)
    @time collect(As ⊕ Bs ⊕ Cs)
    @time kron(A,IB,IC) + kron(IA,B,IC) + kron(IA,IB,C)
    @time kron(As,IBs,ICs) + kron(IAs,Bs,ICs) + kron(IAs,IBs,Cs)

    println("\norder 4")
    @time collect(A ⊕ B ⊕ C ⊕ D)
    @time collect(As ⊕ Bs ⊕ Cs ⊕ Ds)
    @time kron(A,IB,IC,ID) + kron(IA,B,IC,ID) + kron(IA,IB,C,ID) + kron(IA,IB,IC,D)
    @time kron(As,IBs,ICs,IDs) + kron(IAs,Bs,ICs,IDs) + kron(IAs,IBs,Cs,IDs) + kron(IAs,IBs,ICs,Ds)
end

# Checking collection types for ⊗, ⊕ and kron
@test kron(As,IB) isa SparseMatrixCSC
@test collect(As ⊗ Bs) isa SparseMatrixCSC # true for kronecker()
@test (kron(As,IB,IC) + kron(IA,Bs,IC) + kron(IA,IB,Cs)) isa SparseMatrixCSC
#@test collect(As ⊕ Bs) isa SparseMatrixCSC # false for kroneckersum()

```

</details>

Timing output (post-warmup)

<details>
<summary>Click to expand!</summary>

```julia

order 2
  0.000266 seconds (7 allocations: 78.391 KiB)
  0.000325 seconds (7 allocations: 78.391 KiB)
  0.000075 seconds (10 allocations: 234.766 KiB)
  0.000035 seconds (16 allocations: 66.172 KiB)

order 3
  0.030789 seconds (8 allocations: 7.630 MiB)
  0.029933 seconds (8 allocations: 7.630 MiB)
  0.032906 seconds (19 allocations: 30.747 MiB, 45.88% gc time)
  0.000471 seconds (46 allocations: 1.281 MiB)

order 4
  3.523688 seconds (9 allocations: 762.940 MiB, 0.02% gc time)
  3.738714 seconds (9 allocations: 762.940 MiB, 0.47% gc time)
  3.295205 seconds (35 allocations: 3.755 GiB, 11.57% gc time)
  0.007760 seconds (91 allocations: 20.458 MiB)

```



</details>

**Comment by elisno** [comment]
With https://github.com/MichielStock/Kronecker.jl/commit/3ef77155b902d0ce188a595154bf21f0055031c4, performance of `⊕` collection is comparable to `kron`.

But I believe further speedup is gained by performing the evaluation with all matrices as `SparseMatrixCSC`, then collecting the result into some dense array. 

This is especially important for higher order sums, where you have many sparse identity matrices.

**Comment by MichielStock** [comment]
Yes, I think the solution would be that `collect(sparse(A) ⊕ sparse(B) ⊕ sparse(C))` returns a sparse array. I am working at this, it currently works for two matrices, but not for higher order!

**Comment by MichielStock** [comment]
Here: this makes the matrices dense for higher-order collect. Still looking how this might happen. 

https://github.com/MichielStock/Kronecker.jl/blob/fdfedeb7aaa0a6b76b3c327be8aa848cb4b0ebb3/src/kroneckersum.jl#L108-L112

Note that `kron` is now overloaded to also work with `AbstractKroneckerProduct`s:

https://github.com/MichielStock/Kronecker.jl/blob/fdfedeb7aaa0a6b76b3c327be8aa848cb4b0ebb3/src/base.jl#L214-L228

**Comment by elisno** [comment]
Looks promising.
Can you make a PR for tracking changes?

**Comment by MichielStock** [comment]
`collect(K::AbstractKroneckerSum)` now returns the result as a sparse matrix. 

https://github.com/MichielStock/Kronecker.jl/blob/1e78e35df70b26034dd9cf7d1419df25f975d190/src/kroneckersum.jl#L108-L113

What do you think?

**Comment by elisno** [comment]
I think this is the ideal case for `collect(K::AbstractKroneckerSum)`.
It should be well documented that the result is sparse. For dense output, you would have to call collect twice.

I'm guessing this still doesn't cover higher-order sums?

**Comment by MichielStock** [comment]
No, it seems to work fine with any higher-order Kronecker sums.

There might be some room for optimization though.

**Comment by elisno** [comment]
Great! I'd say this is more than enough (for now :wink:).

Perhaps add some  `collect(K) isa ...` tests?

**Comment by MichielStock** [comment]
Done, let’s keep these types!

**Comment by elisno** [comment]
#28 closes this issue.
