### ISSUE TITLE
JuliaCon 2019 paper submission should be in this repo

### ISSUE THREAD

**Issue by christianpeel** [MichielStock/Kronecker.jl#3]
The JuliaCon 2019 Proceedings [instructions for authors](https://proceedings.juliacon.org/guide/authors/) says "We highly encourage the authors to create the /paper folder in their project repository, putting it alongside the code."   I suggest that you follow this instruction and move the paper submission in  https://github.com/MichielStock/JuliaConSubmission.jl into this repo.  Some work with the editor @matbesancon may be required to update the [review issue](https://github.com/JuliaCon/proceedings-review/issues/13) appropriately.

If there is some good reason that you do not merge https://github.com/MichielStock/JuliaConSubmission.jl into this repository, at least you should change it to no longer be a fork of https://github.com/JuliaCon/JuliaConSubmission.jl so that reviewers can actually file issues in that repo as they are supposed to do in the review process.

This is a critical issue and I do not believe the [review](https://github.com/JuliaCon/proceedings-review/issues/13) of the paper can proceed without doing one of the two things above.

**Comment by MichielStock** [comment]
Are extended abstracts for Juliacon also for very-much-work-in-progress (as this package)? Was not clear to me. If ok, I will link the paper to this repo then ASAP.

**Comment by christianpeel** [comment]
I'm a reviewer, not an editor.  All I know is that it doesn't seem like I can do the review with the two repos in the current state.

For context, in the [review issue](https://github.com/JuliaCon/proceedings-review/issues/13) for the proceedings we've been asked to complete our review in two weeks.   For me to complete a review in two weeks, you may need to quickly move beyond a work-in-progress state.

**Comment by matbesancon** [comment]
1. Yes the paper should live with the software when linked to a package like this. I don't think we can re-attach a review to another repo, so you may need to make a new submission linked here
2. I haven't checked the package itself but it should be complete enough to contain the features presented in the abstract

**Comment by christianpeel** [comment]
Thanks for making this change!  It makes the paper easier to review.
