### ISSUE TITLE
Add tests for errors

### ISSUE THREAD

**Issue by elisno** [MichielStock/Kronecker.jl#30]
There's not currently tests to see which error get's thrown if someone tries to compute e.g. the trace of a non-square matrix. Might make sense to add a few `@test_throws DimensionMismatch ...` tests to prevent accidental regressions.

_Originally posted by @willtebbutt in https://github.com/MichielStock/Kronecker.jl/pull/28#issuecomment-516771581_

**Comment by MichielStock** [comment]
Done in 52c378b008fe3be71b817fecf0caa1d20ab13a8e, but any more suggestions for error tests are welcomed!

**Comment by elisno** [comment]
#28 closes this issue.
