### ISSUE TITLE
Register with Pkg

### ISSUE THREAD

**Issue by christianpeel** [MichielStock/Kronecker.jl#4]
If this package is good enough for a JuliaCon talk and for the JuliaCon proceedings, it is definitely good enough to be registered in the Julia package registry. You don't need to claim that it's perfect to register it, start with version v0.1.0.  Using [Registrator](https://github.com/JuliaRegistries/Registrator.jl) is one good thing to do.

**Comment by MichielStock** [comment]
Is currently pending. Will update readme and close when finished.

**Comment by christianpeel** [comment]
I think it's good practice to have a Github 'release' version that matches the version number in the Project.toml file. 

The package is registered; I can see it for example on [pkg.julialang.org](https://pkg.julialang.org/docs/Kronecker/).

Thanks!
