### ISSUE TITLE
Tag new minor release

### ISSUE THREAD

**Issue by willtebbutt** [MichielStock/Kronecker.jl#42]
Would it be possible to tag a new minor version as we now have `KroneckerProduct * Matrix` implemented? Also, are you using the [Julia registrator](https://github.com/JuliaRegistries/Registrator.jl) to tag releases? It makes life very straightforward.

**Comment by MichielStock** [comment]
Done in f5446cc03e360ec2cb047ec23d1f1a3d809856f4
