### ISSUE TITLE
Condition for the multiplication order in the vec-trick

### ISSUE THREAD

**Issue by dkarrasch** [MichielStock/Kronecker.jl#55]
I did some testing for Kronecker multiplications with `LinearMaps.jl`, and found that `Kronecker.jl`'s rule for determining which branch to choose is not always fortunate. I did not understand which heuristic is employed here anyway, but you may wish to consider choosing intermediate memory allocation as the rule (for number of flops some factors are missing). See https://github.com/Jutho/LinearMaps.jl/pull/61#discussion_r344669301 for a simple test script.

**Comment by willtebbutt** [comment]
Thanks for raising this. I agree that it would be interesting to understand why the heuristic is failing to produce good results. Would you mind bumping up the problem size a bit, trying out a `Kronecker-Matrix` multiplication (rather than `Kronecker-Vector`)? Presumably Kronecker.jl's improved asymptotic complexity will win out at some point...

**Comment by dkarrasch** [comment]
I would need to think about how to do kronecker-matrix multiplication within `LinearMaps.jl` first. So without a comparison it may not be easy to tell whether the chosen track was good or bad. I'll get back to you.

**Comment by dkarrasch** [comment]
Hold on, I had this condition in mind:
https://github.com/MichielStock/Kronecker.jl/blob/0e62b2a39531d3687a70a9fa17919099479a9e34/src/vectrick.jl#L42

This is for vectors.

**Comment by willtebbutt** [comment]
> Hold on, I had this condition in mind

Yup. I think this condition makes sense in general, but it's not clear that it's optimal for smaller problems. @MichielStock are you able to comment on this?

> This is for vectors.

Yup, but that same condition is used for [matrices](https://github.com/MichielStock/Kronecker.jl/blob/0e62b2a39531d3687a70a9fa17919099479a9e34/src/vectrick.jl#L63), so should be comparable.

**Comment by dkarrasch** [comment]
But what does this condition estimate anyway? It's not flops, it's not intermediate memory allocation.

**Comment by willtebbutt** [comment]
It should be a proxy for flops based on the size of the matrices involved in the kronecker product. I've never really thought too hard about it and just assumed that it kind of makes sense. Possibly it does not.

**Comment by MichielStock** [comment]
It seems to be a mistake...

`(M o N) * vec(V) = vec(N * V * M')`

`size(M) = (a, b)`
`size(N) = (c, d)`
`size(V) = (d,b)`

So, the cost of parsing

- as  `(N * V) * M'` is order `b*d*c + a*b*c=c*b*(a+d)`
- as `N * (V * M') is order `d*b*a + a * c * d = a * d * (b + c)`

So this was a mistake that was never corrected 😬

I will correct this.

**Comment by dkarrasch** [comment]
You may wish to consider using the even simpler allocation heuristic. I found that the (correct) flops heuristic picks up the more expensive branch in the case that `A` is very tall and `B` is very wide, see my linked comment above. Anyway, maybe one can construct an opposite case, too, which I have missed.

**Comment by MichielStock** [comment]
You mean (in my notation) `d * a < c * b`?

This would be minimizing the memory (size of temporary matrix) rather than the approximate time complexity? I am not really sure what would have more influence in practice. 2cd5269de940751c4212da91e96b7c888b3e58fb is correct for the time complexity.

**Comment by MichielStock** [comment]
@dkarrasch: can I close this?

**Comment by dkarrasch** [comment]
It's all up to you. If you feel comfortable with the time complexity criterion, sure. I just found that it seems to make an unfortunate choice when Kronecker multiplying tall with wide matrices...

**Comment by MichielStock** [comment]
Then I will go with theoretical time complexity!
