### ISSUE TITLE
Tagging new versions etc

### ISSUE THREAD

**Issue by willtebbutt** [MichielStock/Kronecker.jl#73]
Hi @MichielStock hope you're doing well. Looks like 0.4.1 wasn't properly tagged. For example, the following occurs:
```julia
(@v1.5) pkg> add Kronecker@0.4.1
  Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Kronecker [2c470bb0]:
 Kronecker [2c470bb0] log:
 ├─possible versions are: [0.1.0, 0.2.1-0.2.2, 0.3.0-0.3.1, 0.4.0] or uninstalled
 └─restricted to versions 0.4.1 by an explicit requirement — no versions left
```
Would you be able to install [Registrator.jl](https://github.com/JuliaRegistries/Registrator.jl) on this repo so that it can be registered properly? Will make releasing more straightforward. I'm also happy to sort this out if you're happy to give me commit the necessary permissions.

**Comment by MichielStock** [comment]
Hi Will. Oh dear, I added the new registrator. Does this resolve this automatically? 
I think we are due to an increase in version anyway.

**Comment by willtebbutt** [comment]
Not quite. You just need to comment on the commit that you want to tag as v `0.4.1`.

**Comment by MichielStock** [comment]
You are now!

**Comment by willtebbutt** [comment]
Thanks! Do you know which commits you want to tag as 0.4.1 / 0.4.2 etc?

**Comment by MichielStock** [comment]
0.4.1 => 86cf9f0b301f1af8842cea49ba2cc6e2655c5b1a
0.4.2 => ef7647e657eb9b68d722f96b84a5545c871edd40

**Comment by willtebbutt** [comment]
Cool. Are you happy to handle registration?

**Comment by MichielStock** [comment]
I'll try.

**Comment by MichielStock** [comment]
Hmm, something went wrong. I have a version `0.4.0` and `0.4.2` (December), but no version `0.4.1`... Can this still be fixed? Or is it best to start a `0.4.3` for the latest commits?

**Comment by willtebbutt** [comment]
I think probably the easiest thing to do is

1. find the last commit that you want to call 0.4.1 and tag that as 0.4.1.
2. once that's been merged into the registry, delete the 0.4.2 tag from this repo and the latest thing as 0.4.2.

**Comment by willtebbutt** [comment]
> 0.4.1 => 86cf9f0

@michielstock sorry, can I attempt to tag this commit as 0.4.1 then?

**Comment by MichielStock** [comment]
Yes. Sorry, did not yet managed to do it 😬

**Comment by willtebbutt** [comment]
Oh, sorry, just looked at the commit. Hmmmmmmmm

**Comment by willtebbutt** [comment]
Right, looking at the [general registry](https://github.com/JuliaRegistries/General/tree/master/K/Kronecker), it appears that 0.4.1 has somehow been registered, but there's not a tag on this repo for it.

Conversely, there isn't a 0.4.2 available on the general registry, but there is one on this repo. Consequently, I would suggest that you delete the 0.4.2 tag from this repo, and attempt to tag the most recent commit as 0.4.2.

**Comment by willtebbutt** [comment]
Ahhh tagbot isn't installed, that's why there's not a tag for 0.4.1. I'll

1. Find a way to manually tag 0.4.1
2. Install Tagbot so that tagging happens automatically happens in the future (requires a PR)
3. We should probably bump to 0.4.3 and register that as well.

**Comment by willtebbutt** [comment]
Okay, now that TagBot is merged, when [this PR](https://github.com/JuliaRegistries/General/pull/25628) we should get both 0.4.2 on the general registry, and TagBot should make it appear on this repo. If all goes according to plan, we can create 0.4.3 to scoop up and remaining changes if needed, and register that.

Any future releases should be much more straightforward :)

**Comment by MichielStock** [comment]
You're a lifesaver!

**Comment by MichielStock** [comment]
Yes, that sound reasonable.

**Comment by willtebbutt** [comment]
Looks to have worked 🍾 Thanks for assisting with getting this sorted!
